// Подключаем mongoose.
const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/retouchme', { useNewUrlParser: true });

const Task = require('../models/task');

const tasks = [
  {
    status: false,
    approved: true,
    inProgress: false,
    issuedBy: 'Эдвард',
    title: 'Не выполнена и одобрена админом - Нужна ретуш и коллажирование фото',
    info: 'Нужно обработать и частично склеить фото, сделать нужно до вечера.',
    amount: 100,
    cost: 1000,
    link: 'https://www.fl.ru/projects/4170511/nujna-retush-i-kollajirovanie-foto.html',
  },
  {
    status: false,
    approved: true,
    inProgress: false,
    issuedBy: 'Евгения',
    title: 'Не выполнена и одобрена админом - 10 фото',
    info: 'Желательно бы, чтобы было готово вчера, но если сегодня, то тоже ок',
    amount: 10,
    cost: 100,
    link: 'https://www.fl.ru/.html',
  },
  {
    status: false,
    approved: true,
    inProgress: false,
    issuedBy: 'Антон',
    title: 'Не выполнена и одобрена админом - Ретуш 200 фото',
    info: 'Добрый день. Работа на пару часов',
    amount: 200,
    cost: 2000,
    link: 'https://www.ya.ru',
  },
  {
    status: false,
    approved: true,
    inProgress: false,
    issuedBy: 'Алексей',
    title: 'Не выполнена и одобрена админом - 30-40 фото',
    info: 'Нужен ретушер, умеющий работать в технике частотного разложения. Задача – 30-40 фотографий с фотосессии',
    amount: 40,
    cost: 400,
    link: 'https://www.fl.ru/.html',
  },
  {
    status: true,
    approved: true,
    inProgress: false,
    issuedBy: 'client2',
    title: 'Выполнена - ретуш, срочно',
    info: '50 фотографий.',
    amount: 500,
    cost: 5000,
    link: 'https://www.fl.ru/projects/4170469/obrabotka-foto.html',
  },
  {
    status: true,
    approved: true,
    inProgress: false,
    issuedBy: 'Роман Анатольевич',
    title: 'Выполнена - Нужна ретуш, срочно',
    info: '35 фотографий.',
    amount: 35,
    cost: 350,
    link: 'https://www.fl.ru/projects/4170461',
  },
  {
    status: true,
    approved: true,
    inProgress: false,
    issuedBy: 'renata1965',
    title: 'Выполнена - Ретуш',
    info: '100 фотографий.',
    amount: 100,
    cost: 1000,
    link: 'https://www.fl.ru/',
  },
  {
    status: false,
    approved: false,
    inProgress: false,
    issuedBy: 'client3',
    title: 'НЕ одобрена админом - ретуш? А надо ли мне оно..',
    info: 'я просто так зашёл на ваш сайт посмотреть',
    amount: 1,
    cost: 9999,
    link: 'google.com',
  },
  {
    status: false,
    approved: false,
    inProgress: false,
    issuedBy: 'client3',
    title: 'НЕ одобрена админом',
    info: 'spjihvonvpemlfd',
    amount: 1,
    cost: 9999,
    link: 'noadress.com',
  },
  {
    status: false,
    approved: false,
    inProgress: false,
    issuedBy: 'client3',
    title: 'НЕ одобрена админом - !!11kdjvjepo3pflm',
    info: 'lalalalalalalalalalla',
    amount: 9999,
    cost: 1,
    link: 'info.info',
  },
  {
    status: false,
    approved: true,
    inProgress: false,
    issuedBy: 'Эдвард',
    title: 'Не выполнена и одобрена админом - Нужна ретуш и коллажирование фото',
    info: 'Нужно обработать и частично склеить фото, сделать нужно до вечера.',
    amount: 100,
    cost: 1000,
    link: 'https://www.fl.ru/projects/4170511/nujna-retush-i-kollajirovanie-foto.html',
  },
  {
    status: false,
    approved: true,
    inProgress: false,
    issuedBy: 'Евгения',
    title: 'Не выполнена и одобрена админом - 10 фото',
    info: 'Желательно бы, чтобы было готово вчера, но если сегодня, то тоже ок',
    amount: 10,
    cost: 100,
    link: 'https://www.fl.ru/.html',
  },
  {
    status: false,
    approved: true,
    inProgress: false,
    issuedBy: 'Антон',
    title: 'Не выполнена и одобрена админом - Ретуш 200 фото',
    info: 'Добрый день. Работа на пару часов',
    amount: 200,
    cost: 2000,
    link: 'https://www.ya.ru',
  },
  {
    status: false,
    approved: true,
    inProgress: false,
    issuedBy: 'Алексей',
    title: 'Не выполнена и одобрена админом - 30-40 фото',
    info: 'Нужен ретушер, умеющий работать в технике частотного разложения. Задача – 30-40 фотографий с фотосессии',
    amount: 40,
    cost: 400,
    link: 'https://www.fl.ru/.html',
  },
  {
    status: true,
    approved: true,
    inProgress: false,
    issuedBy: 'client2',
    title: 'Выполнена - ретуш, срочно',
    info: '50 фотографий.',
    amount: 500,
    cost: 5000,
    link: 'https://www.fl.ru/projects/4170469/obrabotka-foto.html',
  },
  {
    status: true,
    approved: true,
    inProgress: false,
    issuedBy: 'Роман Анатольевич',
    title: 'Выполнена - Нужна ретуш, срочно',
    info: '35 фотографий.',
    amount: 35,
    cost: 350,
    link: 'https://www.fl.ru/projects/4170461',
  },
  {
    status: true,
    approved: true,
    inProgress: false,
    issuedBy: 'renata1965',
    title: 'Выполнена - Ретуш',
    info: '100 фотографий.',
    amount: 100,
    cost: 1000,
    link: 'https://www.fl.ru/',
  },
  {
    status: false,
    approved: false,
    inProgress: false,
    issuedBy: 'client3',
    title: 'НЕ одобрена админом - ретуш? А надо ли мне оно..',
    info: 'я просто так зашёл на ваш сайт посмотреть',
    amount: 1,
    cost: 9999,
    link: 'google.com',
  },
  {
    status: false,
    approved: false,
    inProgress: false,
    issuedBy: 'client3',
    title: 'НЕ одобрена админом',
    info: 'spjihvonvpemlfd',
    amount: 1,
    cost: 9999,
    link: 'noadress.com',
  },
  {
    status: false,
    approved: false,
    inProgress: false,
    issuedBy: 'client3',
    title: 'НЕ одобрена админом - !!11kdjvjepo3pflm',
    info: 'lalalalalalalalalalla',
    amount: 9999,
    cost: 1,
    link: 'info.info',
  },
  {
    status: false,
    approved: true,
    inProgress: false,
    issuedBy: 'Эдвард',
    title: 'Не выполнена и одобрена админом - Нужна ретуш и коллажирование фото',
    info: 'Нужно обработать и частично склеить фото, сделать нужно до вечера.',
    amount: 100,
    cost: 1000,
    link: 'https://www.fl.ru/projects/4170511/nujna-retush-i-kollajirovanie-foto.html',
  },
  {
    status: false,
    approved: true,
    inProgress: false,
    issuedBy: 'Евгения',
    title: 'Не выполнена и одобрена админом - 10 фото',
    info: 'Желательно бы, чтобы было готово вчера, но если сегодня, то тоже ок',
    amount: 10,
    cost: 100,
    link: 'https://www.fl.ru/.html',
  },
  {
    status: false,
    approved: true,
    inProgress: false,
    issuedBy: 'Антон',
    title: 'Не выполнена и одобрена админом - Ретуш 200 фото',
    info: 'Добрый день. Работа на пару часов',
    amount: 200,
    cost: 2000,
    link: 'https://www.ya.ru',
  },
  {
    status: false,
    approved: true,
    inProgress: false,
    issuedBy: 'Алексей',
    title: 'Не выполнена и одобрена админом - 30-40 фото',
    info: 'Нужен ретушер, умеющий работать в технике частотного разложения. Задача – 30-40 фотографий с фотосессии',
    amount: 40,
    cost: 400,
    link: 'https://www.fl.ru/.html',
  },
  {
    status: true,
    approved: true,
    inProgress: false,
    issuedBy: 'client2',
    title: 'Выполнена - ретуш, срочно',
    info: '50 фотографий.',
    amount: 500,
    cost: 5000,
    link: 'https://www.fl.ru/projects/4170469/obrabotka-foto.html',
  },
  {
    status: true,
    approved: true,
    inProgress: false,
    issuedBy: 'Роман Анатольевич',
    title: 'Выполнена - Нужна ретуш, срочно',
    info: '35 фотографий.',
    amount: 35,
    cost: 350,
    link: 'https://www.fl.ru/projects/4170461',
  },
  {
    status: true,
    approved: true,
    inProgress: false,
    issuedBy: 'renata1965',
    title: 'Выполнена - Ретуш',
    info: '100 фотографий.',
    amount: 100,
    cost: 1000,
    link: 'https://www.fl.ru/',
  },
  {
    status: false,
    approved: false,
    inProgress: false,
    issuedBy: 'client3',
    title: 'НЕ одобрена админом - ретуш? А надо ли мне оно..',
    info: 'я просто так зашёл на ваш сайт посмотреть',
    amount: 1,
    cost: 9999,
    link: 'google.com',
  },
  {
    status: false,
    approved: false,
    inProgress: false,
    issuedBy: 'client3',
    title: 'НЕ одобрена админом',
    info: 'spjihvonvpemlfd',
    amount: 1,
    cost: 9999,
    link: 'noadress.com',
  },
  {
    status: false,
    approved: false,
    inProgress: false,
    issuedBy: 'client3',
    title: 'НЕ одобрена админом - !!11kdjvjepo3pflm',
    info: 'lalalalalalalalalalla',
    amount: 9999,
    cost: 1,
    link: 'info.info',
  },
];

Task.insertMany(tasks).then(() => {
  mongoose.connection.close();
});
